### ISSUE TITLE
Bug in TernaryBooleanLiteral

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1163] opened 2017-03-24 21:21 UTC
```
public Boolean apply(@Nullable Boolean from) {
    return (from == null) ? true : null;
}
```
goes to
```
public Boolean apply(@Nullable Boolean from) {
     return from == null || null;
}
```

**Comment by OriRoth** [comment] 2017-03-24 21:54
There is a utility that tells you if parenthesis are required in an expression.

**Comment by yossigil** [comment] 2017-03-24 22:06
the problems is not parenthesis but the interpretation of null.Null is  a valid Boolean value, but it not
a valid boolean value. To do the transformation, you try to use null is boolean. This is not possible.
It is not poissble. also if instead of null, you had a function of type Boolean (but not boolean), which may have returned a 
null Boolean?

The only correct way to deal with this is to check the type of the arguments. If one of the arguments is of type Boolean, then this tipper must not work. Consult with @NivShalmon , re type information

**Comment by yossigil** [comment] 2017-03-28 01:00
@NivShalmon : Maybe your type class can help here?

**Comment by yossigil** [comment] 2017-04-11 22:31
Duplicate of #181

**Closed** 2017-06-19 14:28 UTC
Labels: bug

**Comment by yossigil** [comment] 2017-06-27 16:41
:100:
