### ISSUE TITLE
Changing the order of widget Operations doesn't work

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Main#1417] opened 2017-05-24 07:46 UTC
Only changes the display order in the upper window, the order in the lower window and the widget don't change. Also, it seems like the actual location of the operations doesn't change. After moving git commint (the 3rd operation) up and then disabling it, I can enable it again from the 3rd operation (now git push) instead of its current position.

**Comment by ravivos** [comment] 2017-05-24 10:44
duplicate of #1402

**Closed by ravivos** 2017-05-24 10:44 UTC
Labels: bug
