### ISSUE TITLE
if-matching else bug

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#1354] opened 2017-05-19 05:08 UTC
```java
  /** Returns the index of the first occurrence of the specified element in this
   * list, or -1 if this list does not contain the element. More formally,
   * returns the lowest index <tt>i</tt> such that
   * <tt>(o==null&nbsp;?&nbsp;get(i)==null&nbsp;:&nbsp;o.equals(get(i)))</tt>,
   * or -1 if there is no such index. [[SuppressSpartanizationTips]] */
  @Override public int indexOf(final Object o) {
    if (o == null)
      for (int $ = 0; $ < size(); ++$) {
        // Spartanization bug here.Cannot remove the curly brackets.
        assert o == null;
        if (data[$] == null)
          return $;
      }
    else
      for (int ¢ = 0; ¢ < size(); ++¢) {
        // Spartanization bug here.Cannot remove the curly brackets.
        assert o != null;
        if (o.equals(data[¢]))
          return ¢;
      }
    return -1;
  }
```

**Comment by NivShalmon** [comment] 2017-05-25 14:00
duplicate of #1410. Since there has been some disccusion there, I'm leaving that one open till it's fixed

**Comment by NivShalmon** [comment] 2017-05-25 14:24
not a duplicate of #1410 after all, subtle diffrence but an entirely different case

**Closed** 2017-05-26 08:19 UTC
Labels: bug
