### ISSUE TITLE
Restoring widget default preferences bug

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1483] opened 2017-06-12 23:18 UTC
It happens when clicking _Restore Defaults_ in OperationsListEditor:
![image](https://user-images.githubusercontent.com/17455055/27059331-8ee119b4-4fde-11e7-802f-cdade2a3a9f7.png)
It gives null pointer exception and corrupts the preferences

**Comment by ravivos** [comment] 2017-06-13 16:43
will check it out ASAP, thx

**Comment by ravivos** [comment] 2017-06-13 16:51
it looks like the problem is in the preferences I get from the store even when I load the defaults (uncommenting line 49 in spartanWidgetHandler)
@NivShalmon, penny for your thoughts?

**Comment by NivShalmon** [comment] 2017-06-13 17:13
What is this array? This isn't the defualt configuration, that's for sure. And it makes sense there would be a null there since the defualt configuration only has 6 operations. This seems to be a problem of some part of the code not supporting having less than 7 operations, not a problem with the default configuration.
We can add a seventh operation to the default configuration (and probably should), but I doubt that would solve this probelm, only make it not happen with the defaults

**Comment by ravivos** [comment] 2017-06-13 17:16
well, here it does look fine but when you change the default pref and the uncomment line 49, it doesn't work and I suspect that when it will be fixed, this issue will also be fixed

**Comment by yuvalsimon** [comment] 2017-06-14 11:53
Still corrupts the preferences @ravivos , maybe should use list instead of array, it shouldn't be always of fixed size of 7

**Comment by ravivos** [comment] 2017-06-16 00:18
now it is fixed.
take note that your old preferences might be corrupted and you will need to reset it.
This is how you can do it:

1.  uncomment line 48 in SpartanWidgetHandler
2. uncomment the line in function "parseString", in OperationListEditor.
3. run the plugin
4. enter the widget
5. enter the pref page of the widget
6. close the plugin and comment back the lines you uncommented.

That's it - your pref has been reset!!

cc: added one more step to @NivShalmon's solution

**Comment by yuvalsimon** [comment] 2017-06-16 01:00
I get ArrayIndexOutOfBoundsException

**Comment by ravivos** [comment] 2017-06-16 01:16
did you restore the preferences?
can you screen shot the exception?
as @OriRoth always says - pics or it didn't happen

**Comment by yuvalsimon** [comment] 2017-06-16 01:30
Yes I restored them..
![image](https://user-images.githubusercontent.com/17455055/27208124-77171c96-524c-11e7-922b-ff00dcc31c95.png)

**Comment by ravivos** [comment] 2017-06-17 19:28
I think I fixed it for good now

**Comment by yuvalsimon** [comment] 2017-06-18 16:43
@ravivos can not remove now operations. When I remove some operations and then add a new one, all the removed operations return to the list as if I haven't removed them at all.

**Closed as completed** 2017-06-28 23:03 UTC
Labels: bug
