### ISSUE TITLE
User configurable renaming Tippers

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#1222] opened 2017-04-06 04:56 UTC
Yuval: Your task, should you choose to accept it, is to add to the configuration window a **radio button** that allows to select the name of the "return" variable, with these options:

- `result`
- `res`
- `ret`
- `typeCamelCase`
- function's name
- Other

If the user selects other, then there is a small text box, in which he can fill his desired name:

FYI @SpartanRefactoring/zoomers 

-

**Comment by OriRoth** [comment] 2017-04-06 05:06
1. May also be applied to lambda and cent
2. A drop down menu would look better in my opinion... it is also possible to use a String editor field
3. This obviously requires modifying the relevant tippers to access preference store. Be sure to do this efficiently!
4. `typeCamelCase` requires special care

**Comment by OriRoth** [comment] 2017-04-06 05:20
@yuvalsimon you may ask a brief introduction to preferences mechanism from me/@dormaayan.

Duplicate of #1162 thus I assign Dor as well.

**Comment by yuvalsimon** [comment] 2017-04-23 16:03
Where should I store the identifier chosen by the user when closing eclipse, to load it in the next activation of eclipse? serializing the class to file/plugin.xml?

**Comment by OriRoth** [comment] 2017-04-23 16:04
PREFERENCE STORE

**Comment by OriRoth** [comment] 2017-04-23 16:16
לא לעשות בלאגאן בבקשה. זה לא אמור לקחת יותר מכמה שורות בודדות במקום המיועד לכך.

**Comment by dormaayan** [comment] 2017-05-01 20:47
@yuvalsimon : I think I solved all the major problems we had in those issues, from now on I'll be on that

**Comment by dormaayan** [comment] 2017-05-02 19:00
I'm done for now, I might extend it in the future

**Closed by dormaayan** 2017-05-02 19:00 UTC
Labels: GUI, Namespace
