### ISSUE TITLE
If there is a tip suggestion and also an intellij warning, the warning won't show.

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Main#1468] opened 2017-06-06 12:03 UTC
Also, a similar mechanism of eclipse warnings for applicable tippers should be added.

**Comment by RoeyMaor** [comment] 2017-06-19 05:10
"a similar mechanism of eclipse warnings for applicable tippers should be added" - could you elaborate?
also, the warnings do show, both in the editor to the right, and upon compilation. the problem is merely the yellow underline that wont show?

**Comment by RoeyMaor** [comment] 2017-06-28 08:08
as we spoke in the meeting, closing

**Closed by RoeyMaor** 2017-06-28 08:08 UTC
Labels: bug, enhancement, Intellij
