### ISSUE TITLE
Bug in BlockSingletonEliminate

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1410] opened 2017-05-23 09:11 UTC
example from guava->list.java->indexOfRandomAccess:
```
  private static int indexOfRandomAccess(List<?> list, @Nullable Object element) {
    int size = list.size();
    if (element == null) {
      for (int ¢ = 0; ¢ < size; ++¢)
		if (list.get(¢) == null)
			return ¢;
    } else
		for (int ¢ = 0; ¢ < size; ++¢)
			if (element.equals(list.get(¢)))
				return ¢;
    return -1;
  }
```
goes to
```
  private static int indexOfRandomAccess(List<?> list, @Nullable Object element) {
    int size = list.size();
    if (element == null)
		for (int ¢ = 0; ¢ < size; ++¢)
			if (list.get(¢) == null)
				return ¢;
			else
		for (int ¢ = 0; ¢ < size; ++¢)
			if (element.equals(list.get(¢)))
				return ¢;
    return -1;
  }
```
the else is now connected to the inner if instead of the outer one

**Comment by OriRoth** [comment] 2017-05-23 10:00
This is an infrastructure/logic bug. You should fix the relevant utility, carefully.

**Comment by ravivos** [comment] 2017-05-23 15:54
@NivShalmon notes it might be "make.PlantingStatement"

**Comment by NivShalmon** [comment] 2017-05-25 08:09
Not a bug in `make.PlantingStatement` but rather in `iz.blockEssential`. Seems to be duplicate of #1354

**Closed** 2017-05-25 19:21 UTC
Labels: bug
